### ISSUE TITLE
use next/previous links to automatically page through dates

### ISSUE THREAD

**Issue by sckott** [ropensci/crevents#4]
if so, then use for allowing somewhat automated paging with `while` loop

**Comment by sckott** [comment]
`next` and `previous` links are given back in response body now

however, they don't necessarily have data in them, so not really helpful right now, moving to next milestone

**Comment by sckott** [comment]
these are gone now

**Comment by afandian** [comment]
But the cursor allows forward pagination.

**Comment by sckott** [comment]
right, i figured as much, just closing this as next/previous are gone
