### ISSUE TITLE
Wrap filter parameters in quotes

### ISSUE THREAD

**Issue by afandian** [ropensci/crevents#7]
Filter parameters can be supplied in quoted form. This is useful in cases where delimiters need to be included in values, e.g.

    http://query.eventdata.crossref.org/events?filter=subj-id:%22https://www.sciencenews.org/article/massive-red-dead-galaxy-spotted-young-universe%22

I suggest wrapping all filter params in quotes by default (and escaping quotes within the quotes). More info in the [query docs](https://www.eventdata.crossref.org/guide/service/query-api/).

**Comment by sckott** [comment]
thanks @afandian , will do

**Comment by sckott** [comment]
@afandian is this still the case that filter params should be in quotes?
